version: '3'

services:

  exchange:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - "8080:8080"
        - "9090:9090"
      deploy:
        mode: replicated
        replicas: 1
      environment:
        DB_SOURCE: "postgres://root:secret@postgres:5432/go_exchange?sslmode=disable"

  postgres:
    image: 'postgres:14.7'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go_exchange
