DROP TABLE IF EXISTS "entries";
DROP TABLE IF EXISTS "trades";
DROP TABLE IF EXISTS "transfers";
DROP TABLE IF EXISTS "bids";
DROP TABLE IF EXISTS "asks";
DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "users";