// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAsk(ctx context.Context, arg CreateAskParams) (Ask, error)
	CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetAsk(ctx context.Context, id int64) (Ask, error)
	GetBid(ctx context.Context, id int64) (Bid, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTrade(ctx context.Context, id int64) (Trade, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListAllAsks(ctx context.Context, arg ListAllAsksParams) ([]ListAllAsksRow, error)
	ListAllBids(ctx context.Context, arg ListAllBidsParams) ([]ListAllBidsRow, error)
	ListAsks(ctx context.Context, arg ListAsksParams) ([]Ask, error)
	ListBids(ctx context.Context, arg ListBidsParams) ([]Bid, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTradableAsks(ctx context.Context, arg ListTradableAsksParams) ([]Ask, error)
	ListTradableBids(ctx context.Context, arg ListTradableBidsParams) ([]Bid, error)
	ListTrades(ctx context.Context, arg ListTradesParams) ([]Trade, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAsk(ctx context.Context, arg UpdateAskParams) (Ask, error)
	UpdateBid(ctx context.Context, arg UpdateBidParams) (Bid, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
